# -*- coding: utf-8 -*-
"""CLOCK_Weather_and_Time.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zQyvnkgvPk1bLGb0oaFIA-xV-4eN6ws4
"""

# Tested on REPL.it: https://replit.com/@theedoctaz/FlusteredQuaintSpool#main.py

import pygame
import requests
import time
from datetime import datetime

# Initialize Pygame
pygame.init()
pygame.font.init()

# Constants
WIDTH, HEIGHT = 640, 400 #1280,800
BACKGROUND_COLOR = (30, 30, 30)
TEXT_COLOR = (255, 255, 255)
OUTLINE_COLOR = (0, 0, 0)
FONT_SIZE = 40

# Set up the display
screen = pygame.display.set_mode((WIDTH, HEIGHT))
pygame.display.set_caption("Clock and Weather")
bg = pygame.image.load("i_love_ny.jpg") # background image
bw, bh = bg.get_size()
bg = pygame.transform.scale(bg, (bw/6, bh/6))

# Load font
clock_font = pygame.font.Font("ds_digital/DS-DIGIB.TTF", int(FONT_SIZE*3))
clock_outline = pygame.font.Font("ds_digital/DS-DIGIB.TTF", FONT_SIZE*2+10) # doesn't work. TODO: gray translucent background or outlined font.
font = pygame.font.Font("ds_digital/DS-DIGI.TTF", FONT_SIZE)


# Function to get the current time from the Time and Date API
def get_current_time():
    currentDateAndTime = datetime.now()
    date = currentDateAndTime.strftime("%Y-%m-%d")
    time = currentDateAndTime.strftime("%H:%M:%S")
    return date, time

# Function to get weather data from the National Weather Service
def get_weather_data():
    grid_id = "50,77"
    nws_url = f"https://api.weather.gov/gridpoints/BOU/{grid_id}/forecast"

    response = requests.get(nws_url)
    if response.status_code == 200:
        data = response.json()
        periods = data['properties']['periods']
        # Get the first period's details
        if periods:
            today = periods[0]
            # print(today.keys())
            print(today['temperatureTrend'])
            temp = today['temperature']
            # low_temp = today['temperatureLow']
            icon_url = today['icon']
            return temp, icon_url
    return None, None

# Function to fetch and display the weather icon
def load_weather_icon(icon_url):
    try:
        response = requests.get(icon_url)
        if response.status_code == 200:
            with open("icon.png", "wb") as f:
                f.write(response.content)
            return pygame.image.load("icon.png")
    except Exception as e:
        print("Error loading weather icon:", e)
    return None

# Main loop
running = True
while running:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False

    # Clear the screen
    screen.fill(BACKGROUND_COLOR)
    screen.blit(bg, (0, 0))

    # Get current time and weather data
    date, current_time = get_current_time()

    # TODO: get weather update every hour
    temp, icon_url = get_weather_data()
    weather_icon = load_weather_icon(icon_url)

    # Draw the clock
    if current_time:
        time_outline = clock_outline.render(str(current_time), True, OUTLINE_COLOR)
        time_surface = clock_font.render(str(current_time), True, TEXT_COLOR)
        screen.blit(time_surface, (20, HEIGHT // 1.9 + 40))

    # Draw the weather information
    if temp is not None:
        weather_info_surface = font.render(f"Temp: {temp} F", True, TEXT_COLOR)#(f"Temp: {temp} °F", True, TEXT_COLOR)
        screen.blit(weather_info_surface, (WIDTH // 1.5 + 40, HEIGHT // 1.9 + 150))

    # Draw the weather icon
    if weather_icon:
        screen.blit(weather_icon, (WIDTH // 1.5 + 100, HEIGHT // 1.9 + 50))

    # Update the display
    pygame.display.flip()

    # Delay to limit the refresh rate
    time.sleep(1)

# Quit Pygame
pygame.quit()

today.keys()

